### ISSUE TITLE
support for federated graphs?

### ISSUE THREAD

**Issue by scottmccaskill** [n1ru4l/graphql-public-schema-filter#52]
Not sure if this is really an issue as you might define it, but I can't figure out how to use this great package with a federated graph and Apollo server/gateway. Is it possible? Feel free to close if my problem is irrelevant.

**Comment by n1ru4l** [comment]
Do I understand correctly that the individual services Schemas should be annotated and the gateway then enforces those rules?

**Comment by scottmccaskill** [comment]
I think that's how I'd planned to do it, yes. Is there a better/different way?

**Comment by n1ru4l** [comment]
I have not investigated on that yet (and never used federation), but here my thoughts on how it might work.

Directive/field/object/argument extensions information is not exposed via introspection, thus you need another way of exposing that information. One possible option might be via the extensions field on the execution result.

So of your gateway sends a introspection Query to your service you could expose that information via extensions on that introspection result.

The gatway could them use that information with a custom isPublic function 🤔

**Comment by scottmccaskill** [comment]
Sorry - family event took me away from the computer. Thanks for the prompt reply.
So create a plugin on the gateway side to add a custom isPublic function? Is that the route you would suggest?

**Comment by n1ru4l** [comment]
@scottmccaskill Yes, I would do that!

**Comment by n1ru4l** [comment]
Gonna close this as it is answered.
